### PR TITLE
Measure the performance of unit calculations

### PR DESCRIPTION
**Pull request by ejeffrey**
Run some tests of the unit code for performance so we can track how it changes over time.

### CODE REVIEW

**Comment by ejeffrey** [comment]
This isn't ready to merge, it needs to get integrated with teamcity so we can plot performance vs. time.

**Comment by ejeffrey** [comment]
bump @maffoo

**Comment by maffoo** [comment]
Ok, I think I'm done getting things set up nicely with teamcity. @ejeffrey, please take a look and then I'll squash everything and merge. Build results are here: https://matrix-reloaded.physics.ucsb.edu/teamcity/viewType.html?buildTypeId=Pyle_PythonPerformanceTests&tab=buildTypeStatistics&branch_Pyle=__all_branches__

**Comment by ejeffrey** [comment]
LGTM

**Pull request merged**
