### PR TITLE
Fix labrad.util.syncRunServer to run server shutdown hooks.

### LINKED ISSUE #153: syncRunServer does not execute stopServer method
Minimal example:
```python
from labrad.server import LabradServer
import time

class StoppingServer(LabradServer):
    name = "stop not run server"

    def initServer(self):
        print "Starting."

    def stopServer(self):
        print "Stopping"

__server__ = StoppingServer()

if __name__ == '__main__':
    from labrad.util import syncRunServer
    with syncRunServer(__server__):
        print "Server is running, waiting 1 second and exiting."
        time.sleep(1.0)
        print "Done.  Server should stop."
```
prints
```
Starting.
Server is running, waiting 1 second and exiting.
Done.  Server should stop.
Connection was closed cleanly.
```
The server's stopServer method does not appear to be executed.

### PR DESCRIPTION
**Pull request by maffoo**
Fixes #153

### CODE REVIEW

**Comment by chrismacklin** [comment]
Awesome!

**Comment by DanielSank** [comment]
@chrismacklin don't be afraid to review pull requests.

**Comment by chrismacklin** [comment]
I'm not familiar enough with the twisted stuff yet to be able to review the code changes.  It certainly fixes my minimal example.  In the spirit of "find a bug -> write a test -> squash the bug" I considered writing and pushing a test, but I can't decide on a great way to do that here as the server is off running in another thread.  Could be easily done through the file system, but I'm guessing there is probably a more elegant way to achieve this.

**Comment by maffoo** [comment]
Added a test for checking that syncRunServer properly calls the shutdown method. I used a `threading.Event` object to check from across the thread boundary that the method was properly called. Generally, the stuff in the `threading` package is your friend :)

**Comment by chrismacklin** [comment]
Bump?  Can this be merged?

**Comment by maffoo** [comment]
I'm just waiting for the official "LGTM" from someone or other. @chrismacklin, @DanielSank?

**Comment by chrismacklin** [comment]
Looks "Party Time, Excellent" To Merge

image

**Comment by maffoo** [comment]
thanks @chrismacklin for the official signoff (I think?) :)

**Comment by DanielSank** [comment]
Should we consider "I have no idea what I'm doing" Dog as the official mascot of LabRAD?

**Comment by maffoo** [comment]
only if he is a LabRADor.

**Pull request merged**
