### PR TITLE
Update node to handle multiple versions of same server.

### PR DESCRIPTION
**Pull request by maffoo**
When scanning for server configs, the node used to take the first config it encountered for a particular server name and drop any subsequent configs for the same server name. We change this behavior so that all configs for a given server name are kept, but with the version appended to the name for older versions to keep the names unique. The most recent version keeps its name in unmodified form. So, for example, if you have `my-server` versions 1.0, 1.1 and 1.2 in the node search path, then the node will show: `my-server`, `my-server-1.0` and `my-server-1.1`. Just starting `my-server` will run the latest version, 1.2, but the others will be available as well if needed.

### CODE REVIEW

**Comment by ejeffrey** [comment]
Three questions:

1) What happens with two servers with the same version string?
2) Does the node still wait for the un-decorated server name to appear on the manager?
3) If you try to start v1.2, will it automatically shut down v1.1, or at least return an understandable error to the client so that the client knows what server to shut down before starting the new version?

**Comment by maffoo** [comment]
@ejeffrey:

1. Currently, the node takes the first config it sees for a particular server name, and silently discards any subsequent configs. With this change, if the node finds multiple configs with the same name *and* version, it logs a warning, and then keeps the first config it found.
2. Yes, for each server the node has a `name`, which is what appears in the list of servers, and an `instancename`, which is what it waits for when the server actually runs. This is essential for the local servers, which have a different instance name depending on what node they run on, but we also use this for the single- and multi-headed datavaults, which have different names but the same instancename.
3. No, the node does not do anything special like shutdown old versions. You'd get an error indicating that a server of the given name is already running. Changing this would require more extensive changes to the node, and possibly also coordinated changes to the web interface, depending on how exactly we want things to work.

**Comment by ejeffrey** [comment]
OK, then LGTM on these changes.

On 3, does that error get propagated to and exposed by the web interface, or does it just fail to start?  The old web interface just failed to start with no error message, but I don't know if that was a problem with the web interface or the node.

**Comment by maffoo** [comment]
@ejeffrey, the old web interface logged the error on a different tab; the new one currently logs it in the dev console. Neither is particularly helpful :) I've filed an issue to fix this: labrad/scalabrad-web#169

**Pull request merged**
