### PR TITLE
Expose some underlying ndarray attributes through ValueArray.

### LINKED ISSUE #110: ValueArray should have a .shape attribute
just like ndarray.

### PR DESCRIPTION
**Pull request by chrismacklin**
Implemented as properties.  Closes #110

### CODE REVIEW

**Comment by DanielSank** [comment]
Looks ok. @ejeffrey is the resident expert in dealing with numpy...

**Comment by ejeffrey** [comment]
LGTM

**Comment by chrismacklin** [comment]
bump?

**Comment by DanielSank** [comment]
Ah, I'm guessing @chrismacklin bumped this because he can't merge on the main pylabrad repo. I'll do it.

This obviously highlights the need for a real contributor group. However, I hesitate to do this before we have a document spelling out the contributing workflow. Let's make it a priority to do that.

**Comment by DanielSank** [comment]
Merged via command line.

**Pull request closed without merging**
