### PR TITLE
Remove twistd module support, and labrad_postinstall script

### PR DESCRIPTION
**Pull request by ejeffrey**
When you do 'setup.py install', pylabrad was installing a module into twisted that enabled starting the node with the twistd command, a utility for running twisted service daemons.  However, you can now start twisted directly by executing its __init__.py as a script or by using 'python -m labrad.node.__init__', and we weren't actually using any of the features that twistd provides.  This removes that module, removes the bits from setup.py that were installing it, and removes the labrad_postinstall.py script that didn't do anything.

### CODE REVIEW

**Comment by jwenner** [comment]
Does the node shortcut in martinisgroup/pyle/pyle/tools need to be changed as well?

**Comment by maffoo** [comment]
I was looking at the shortcuts to see how we could modify them, and came across python's -m option, which executes a module or package directly (for packages you have to add a `__main__.py` file to make the package executable by this mechanism). I've pushed the change here: 1b2227b763d1d925426843914432b22f666cd87b. With that, we could just run `python -m labrad.node` to launch the node, which is nice because it uses the python path to locate the module, rather than needing to know the absolute path to `labrad/node/__init__.py`. It will be straightforward to modify the shortcuts jim mentioned to use this mechanism as well.

**Comment by ejeffrey** [comment]
Yes, that is the way to do it.  I haven't actually merged this because
there are some other issues in the install scripts and so forth.

Evan

**Comment by ejeffrey** [comment]
I cherry-picked https://github.com/labrad/pylabrad/commit/1b2227b763d1d925426843914432b22f666cd87b and also fixed the build error due to a reference to labrad_postinstall.sh in setup.cfg.

**Comment by maffoo** [comment]
LGTM

**Pull request merged**
