### PR TITLE
Fix for numpy array_priority issue

### PR DESCRIPTION
**Pull request by ejeffrey**
This cherry-picks the commit from PR #143, adds a new test, and fixes the bug.

### CODE REVIEW

**Comment by DanielSank** [comment]
It's probably worth modifying the doc string:
```
"""
DimensionlessX needs to support all arithmetic operations when the
other side is an array.
"""
```
to note that the numpy float64 and friends are treated as arrays.

**Comment by ejeffrey** [comment]
Updated

**Comment by DanielSank** [comment]
Awesome. LGTM.

**Comment by DanielSank** [comment]
Oh actually one more thing: might want to explain in the actual code why those methods need to be there.

**Pull request merged**
