### PR TITLE
Allow numpy int array to be flattened to labrad *v

### LINKED ISSUE #216: Integer arrays can't be flattened to float arrays
```
In [157]: from labrad import types

In [158]: x = np.array([1, 2, 3, 4, 5])

In [159]: types.flatten(x, '*v')
---------------------------------------------------------------------------
FlatteningError                           Traceback (most recent call last)
<ipython-input-159-9e58ae8ec33d> in <module>()
----> 1 types.flatten(x, '*v')

U:\Pedram\pylabrad\labrad\types.pyc in flatten(obj, types, endianness)
    335         s, t = obj.__lrflatten__(endianness)
    336     else:
--> 337         s, t = _flatten_to(obj, types, endianness)
    338     return FlatData(s, t)
    339

U:\Pedram\pylabrad\labrad\types.pyc in _flatten_to(obj, types, endianness)
    391                     break
    392             if s is None:
--> 393                 raise FlatteningError(obj, types)
    394     return s, t
    395

FlatteningError: (12345) Could not flatten array([1, 2, 3, 4, 5]) to ['*v']. [pa
yload=None]
> u:\pedram\pylabrad\labrad\types.py(393)_flatten_to()
    392             if s is None:
--> 393                 raise FlatteningError(obj, types)
    394     return s, t

ipdb>
```

### PR DESCRIPTION
**Pull request by maffoo**
Fixes #216

### CODE REVIEW

**Comment by DanielSank** [comment]
Where does `unit=None` happen in the code?

**Comment by ejeffrey** [comment]
I think it is still possible to have unit=None in a setting data type (for
instance, the data vault) indicating that the setting accepts floating
point data with any possible unit (i.e., it works like '?').  However, when
you flatten actual data it will generate a type tag that has the units you
pass into it.  So it is possible to have a LRValue object with units=None,
but when you call its __flatten__ method, it will return a type tag v[].

**Comment by maffoo** [comment]
@DanielSank, very specifically it happens here: https://github.com/labrad/pylabrad/blob/master/labrad/types.py#L737

**Comment by DanielSank** [comment]
LGTM

**Pull request merged**
