### PR TITLE
U/ejeffrey/custom unit

### LINKED ISSUE #46: counts unit
It would be helpful to include "counts" as a unit.  For example when working with a PMT it is nice to use kiloCounts/second, or sometimes you want to just save with the unit "counts", for the total counts obtained in an experiment.

<enhancement>

### PR DESCRIPTION
**Pull request by ejeffrey**
This improves handling of non-SI equivalent units (i.e., quantities that are not derived from length, time, mass, current, temperature, mole, luminous intensity, angle, or solid angle).

This could be something like 'count' or 'bytes'.

This allows non-standard units to have derived units So for instance you can have Mcount or kbyte/s and have them work as expected.

This also includes a function addNonSI() that can create these units including the use of SI-style prefixes.

This fixes #46

### CODE REVIEW

**Comment by maffoo** [comment]
By not including `lex_names` in the unit name, this breaks some things:
```python
In [1]: import labrad.units as U

In [2]: U.Unit('tshirt/s')
Out[2]: <Unit 's^-1'>

In [3]: U.Unit('tshirt')/U.s
Out[3]: <Unit 's^-1'>
```

By contrast, in master I can do:
```python
In [1]: import labrad.units as U

In [2]: U.Unit('tshirt/s')
Out[2]: <Unit 'tshirt/s'>

In [3]: U.Unit('tshirt')/U.s
Out[3]: <Unit 'tshirt/s'>

In [4]: (1*U.Unit('tshirt/s'))['tshirt/h']
Out[4]: 3600.0

In [5]: (1*U.Unit('tshirt')/U.s)['tshirt/h']
Out[5]: 3600.0
```

The idea for `lex_names` is to capture parts of the unit that are not in our unit registry when we get arbitrary textual units (e.g. when unflattening labrad data). A change like this would require preregistering any such names before using them.

**Comment by ejeffrey** [comment]
Hi Matthew,

The intent of this update is to have everything in lex_names also in
names.  The idea is that lex_names is the equivalent of the powers
attribute, and stores custom base units, while names stores the printed
version of both the SI derived units and the custom units.  Obviously I
need to look more carefully at catching all the code paths that set names.

Evan

**Comment by ejeffrey** [comment]
OK, I pushed a fix for this along with a test.

**Comment by maffoo** [comment]
One comment about an additional test, otherwise LGTM. It might be good to add some additional documentation about the internals of the `Unit` class, but I think that was also true before this change...

**Comment by ejeffrey** [comment]
Added that test and also a long comment about the structure of the Unit object.  I also fixed a bug I noticed incidentally that made Unit('rad*m/s').isAngle() return true because it did sum(powers) rather than checking that they were all zero individually.

**Comment by ejeffrey** [comment]
@jayich can you let me know when you try this out if it works the way you expect?

**Comment by jayich** [comment]
@ejeffrey , yes, I will try this out within the next and give feedback.

**Comment by ejeffrey** [comment]
The teamcity performance test doesn't show any performance drop from this.

**Comment by jayich** [comment]
@ejeffrey simple question:  If I want to switch branches when working with the labrad repository, what are the correct steps to do this?  Do I need to re-run python setup.py install after switching branches within git?

Currently for example addNonSI is not a method of units but I am on the custom_unit branch.  This is a basic question that I get stuck on from time-to-time.

**Comment by maffoo** [comment]
If you're doing a lot of development and switching branches, the easiest thing is probably just to add the repo directory to your PYTHONPATH environment variable; then whatever version you have checked out will be what you get when you import and run. Generally if you just rerun setup.py that will work, but that can leave old files from previous versions that were installed, so it may leave you with things in an indeterminate state. If you want to install, I would suggest using `pip`; then you can `pip uninstall labrad` before doing `pip install` to make sure you get a clean install. `pip` also works in virtualenvs, if that's your thing.

**Comment by jayich** [comment]
@ejeffrey , this works as I would expect.  Looks great.

**Comment by jayich** [comment]
@maffoo, thank you for the path environment variable suggestion.  It is enabling information.

**Comment by jayich** [comment]
There is an LGTM from @maffoo  above, is there anything else that needs to be done before merging?

**Comment by ejeffrey** [comment]
Nope.  I just missed that you had tested it.  Thanks for the ping.

**Comment by jayich** [comment]
good deal.  Thanks @ejeffrey a bunch for this work.

**Pull request merged**
